### ISSUE TITLE
Error with Meteor

### ISSUE THREAD

**Issue by soulmachine** [davidtsai/node-geoip2#19]
I'm using this package with Meteor, however, I get the following error:

```
meteor-tool/.1.4.2_3.54trdb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20161124-01:40:17.113(-8)? (STDERR) 						throw(ex);
W20161124-01:40:17.114(-8)? (STDERR) 						^
W20161124-01:40:17.114(-8)? (STDERR)
W20161124-01:40:17.114(-8)? (STDERR) Error: Module version mismatch. Expected 46, got 48.
W20161124-01:40:17.114(-8)? (STDERR)     at Error (native)
W20161124-01:40:17.115(-8)? (STDERR)     at Object.Module._extensions..node (module.js:434:18)
W20161124-01:40:17.115(-8)? (STDERR)     at Module.load (module.js:343:32)
W20161124-01:40:17.115(-8)? (STDERR)     at Function.Module._load (module.js:300:12)
W20161124-01:40:17.115(-8)? (STDERR)     at Module.require (module.js:353:17)
W20161124-01:40:17.115(-8)? (STDERR)     at require (internal/module.js:12:17)
W20161124-01:40:17.116(-8)? (STDERR)     at Object.<anonymous> (/Users/soulmachine/github/myapp/node_modules/geoip2/node-geoip2.js:2:12)
W20161124-01:40:17.116(-8)? (STDERR)     at Module._compile (module.js:409:26)
W20161124-01:40:17.116(-8)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20161124-01:40:17.116(-8)? (STDERR)     at Module.load (module.js:343:32)
=> Exited with code: 1
```

It looks like a version mismatch error,  I tried `npm rebuild` but this error still exits.

**Comment by knoxcard** [comment]
https://github.com/runk/node-maxmind/wiki/Most-Efficient-Integration-Methods
