### ISSUE TITLE
node_mmdb.node Exec format error

### ISSUE THREAD

**Issue by SalvoLunar** [davidtsai/node-geoip2#26]
I'm getting this error when using this package on docker node:8.5.0-alpine:

web_1  | Error: Error loading shared library /home/nodeusr/ropo/node_modules/geoip2/lib/node_mmdb.node: Exec format error
web_1  |     at Object.Module._extensions..node (module.js:653:18)
web_1  |     at Module.load (module.js:545:32)
web_1  |     at tryModuleLoad (module.js:508:12)
web_1  |     at Function.Module._load (module.js:500:3)
web_1  |     at Module.require (module.js:568:17)
web_1  |     at require (internal/module.js:11:18)
web_1  |     at Object.<anonymous> (/home/nodeusr/ropo/node_modules/geoip2/node-geoip2.js:2:12)
web_1  |     at Module._compile (module.js:624:30)
web_1  |     at Object.Module._extensions..js (module.js:635:10)
web_1  |     at Module.load (module.js:545:32)

I've been looking everywhere for a fix with no luck.

Can you help?

Cheers,
Salvo

**Comment by knoxcard** [comment]
https://github.com/runk/node-maxmind/wiki/Most-Efficient-Integration-Methods
