### ISSUE TITLE
Error installing on Centos 6.7

### ISSUE THREAD

**Issue by abhijeetshah** [davidtsai/node-geoip2#4]
I am getting following error while installing on CentOS, please help ...

$ npm install node-geoip2 --save
npm WARN package.json passport@0.3.2 No README data
 
> node-geoip2@0.10.1 install /home/as/sails/z2/node_modules/node-geoip2
> node-gyp rebuild

make: Entering directory `/home/as/sails/z2/node_modules/node-geoip2/build'
  CC(target) Release/obj.target/libmaxminddb/deps/libmaxminddb/src/maxminddb.o
  AR(target) Release/obj.target/deps/maxminddb.a
  COPY Release/maxminddb.a
  CXX(target) Release/obj.target/node_mmdb/src/node_mmdb.o
../src/node_mmdb.cpp: In function ‘void init(v8::Handle<v8::Object>)’:
../src/node_mmdb.cpp:275:68: error: could not convert ‘mmdbTpl’ from ‘v8::Handle<v8::FunctionTemplate>’ to ‘v8::Local<v8::FunctionTemplate>’
     Nan::SetPrototypeMethod(mmdbTpl, "lookup",     NodeMMDB::Lookup);
                                                                    ^
../src/node_mmdb.cpp:276:72: error: could not convert ‘mmdbTpl’ from ‘v8::Handle<v8::FunctionTemplate>’ to ‘v8::Local<v8::FunctionTemplate>’
     Nan::SetPrototypeMethod(mmdbTpl, "lookupSync", NodeMMDB::LookupSync);
                                                                        ^
make: *** [Release/obj.target/node_mmdb/src/node_mmdb.o] Error 1
make: Leaving directory `/home/as/sails/z2/node_modules/node-geoip2/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 2.6.32-573.12.1.el6.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/as/sails/z2/node_modules/node-geoip2
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok 
npm ERR! node-geoip2@0.10.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-geoip2@0.10.1 install script.
npm ERR! This is most likely a problem with the node-geoip2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-geoip2
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.32-573.12.1.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-geoip2" "--save"
npm ERR! cwd /home/as/sails/z2
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/as/sails/z2/npm-debug.log
npm ERR! not ok code 0

Please help

**Comment by abhijeetshah** [comment]
Clsong this issue. Was able to solve by upgrading node to 0.12.7
